import {
  Accordion,
  ActionBar,
  Alert,
  AnchorButton,
  AnchorList,
  Autocomplete,
  Banner,
  Button,
  ButtonGroup,
  ButtonList,
  Calendar,
  Card,
  CharacterCount,
  Checkbox,
  CheckboxGroup,
  Clock,
  CoachMark,
  ColorInput,
  ColumnView,
  CycleButton,
  Datepicker,
  Dialog,
  Drawer,
  FileUpload,
  Icon,
  List,
  Masonry,
  Multifield,
  NumberInput,
  Overlay,
  Panel,
  PanelStack,
  Popover,
  Progress,
  QuickActions,
  Radio,
  RadioGroup,
  RangedSlider,
  Search,
  Select,
  SelectList,
  Shell,
  SideNav,
  Slider,
  SplitButton,
  Status,
  Step,
  StepList,
  Switch,
  Tab,
  Table,
  TabList,
  TabView,
  Tag,
  TagList,
  Textarea,
  Textfield,
  Toast,
  Tooltip,
  Tree,
  TreeItem,
  Wait,
  WizardView,
} from '@adobe/coral-spectrum';

const coralComponents = [
  { tagName: 'coral-accordion', component: Accordion },
  // { tagName: 'coral-accordion-item', component: AccordionItem },
  { tagName: 'coral-actionbar', component: ActionBar },
  // { tagName: 'coral-actionbar-container', component: ActionBarContainer },
  // { tagName: 'coral-actionbar-item', component: ActionBarItem },
  // { tagName: 'coral-actionbar-primary', component: ActionBarPrimary },
  // { tagName: 'coral-actionbar-secondary', component: ActionBarSecondary },
  { tagName: 'coral-alert', component: Alert },
  { tagName: 'coral-anchorbutton', component: AnchorButton, extendsElement: 'a' },
  { tagName: 'coral-anchorlist', component: AnchorList },
  // { tagName: 'coral-anchorlist-item', component: AnchorListItem, extendsElement: 'a' },
  { tagName: 'coral-autocomplete', component: Autocomplete },
  // { tagName: 'coral-autocomplete-item', component: AutocompleteItem },
  { tagName: 'coral-banner', component: Banner },
  { tagName: 'coral-button', component: Button, extendsElement: 'button' },
  { tagName: 'coral-buttongroup', component: ButtonGroup },
  { tagName: 'coral-buttonlist', component: ButtonList },
  // { tagName: 'coral-buttonlist-item', component: ButtonListItem, extendsElement: 'button' },
  { tagName: 'coral-calendar', component: Calendar },
  { tagName: 'coral-card', component: Card },
  // { tagName: 'coral-card-property', component: CardProperty },
  // { tagName: 'coral-card-propertylist', component: CardPropertyList },
  { tagName: 'coral-charactercount', component: CharacterCount },
  { tagName: 'coral-checkbox', component: Checkbox },
  { tagName: 'coral-checkboxgroup', component: CheckboxGroup },
  { tagName: 'coral-clock', component: Clock },
  { tagName: 'coral-coachmark', component: CoachMark },
  { tagName: 'coral-colorinput', component: ColorInput },
  // { tagName: 'coral-colorinput-colorproperties', component: ColorInputColorProperties },
  // { tagName: 'coral-colorinput-item', component: ColorInputItem },
  // { tagName: 'coral-colorinput-slider', component: ColorInputSlider },
  // { tagName: 'coral-colorinput-swatch', component: ColorInputSwatch },
  // { tagName: 'coral-colorinput-swatches', component: ColorInputSwatches },
  { tagName: 'coral-columnview', component: ColumnView },
  // { tagName: 'coral-columnview-column', component: ColumnViewColumn },
  // { tagName: 'coral-columnview-item', component: ColumnViewItem },
  // { tagName: 'coral-columnview-preview', component: ColumnViewPreview },
  { tagName: 'coral-cyclebutton', component: CycleButton },
  // { tagName: 'coral-cyclebutton-action', component: CycleButtonAction },
  // { tagName: 'coral-cyclebutton-item', component: CycleButtonItem },
  { tagName: 'coral-datepicker', component: Datepicker },
  { tagName: 'coral-dialog', component: Dialog },
  { tagName: 'coral-drawer', component: Drawer },
  { tagName: 'coral-fileupload', component: FileUpload },
  { tagName: 'coral-icon', component: Icon },
  { tagName: 'coral-list', component: List },
  // { tagName: 'coral-list-divider', component: ListDivider },
  // { tagName: 'coral-list-item', component: ListItem },
  { tagName: 'coral-masonry', component: Masonry },
  // { tagName: 'coral-masonry-item', component: MasonryItem },
  { tagName: 'coral-multifield', component: Multifield },
  // { tagName: 'coral-multifield-item', component: MultifieldItem },
  { tagName: 'coral-numberinput', component: NumberInput },
  { tagName: 'coral-overlay', component: Overlay },
  { tagName: 'coral-panel', component: Panel },
  { tagName: 'coral-panelstack', component: PanelStack },
  { tagName: 'coral-popover', component: Popover },
  // { tagName: 'coral-popover-separator', component: PopoverSeparator },
  { tagName: 'coral-progress', component: Progress },
  { tagName: 'coral-quickactions', component: QuickActions },
  // { tagName: 'coral-quickactions-item', component: QuickActionsItem },
  { tagName: 'coral-radio', component: Radio },
  { tagName: 'coral-radiogroup', component: RadioGroup },
  { tagName: 'coral-rangedslider', component: RangedSlider },
  { tagName: 'coral-search', component: Search },
  { tagName: 'coral-select', component: Select },
  // { tagName: 'coral-select-item', component: SelectItem },
  { tagName: 'coral-selectlist', component: SelectList },
  // { tagName: 'coral-selectlist-group', component: SelectListGroup },
  // { tagName: 'coral-selectlist-item', component: SelectListItem },
  { tagName: 'coral-shell', component: Shell },
  // { tagName: 'coral-shell-header', component: ShellHeader },
  // { tagName: 'coral-shell-help', component: ShellHelp },
  // { tagName: 'coral-shell-help-item', component: ShellHelpItem, extendsElement: 'a' },
  // { tagName: 'coral-shell-homeanchor', component: ShellHomeAnchor, extendsElement: 'a' },
  // { tagName: 'coral-shell-menu', component: ShellMenu },
  // { tagName: 'coral-shell-menubar', component: ShellMenuBar },
  // { tagName: 'coral-shell-menubar-item', component: ShellMenuBarItem },
  // { tagName: 'coral-shell-organization', component: ShellOrganization },
  // { tagName: 'coral-shell-orgswitcher', component: ShellOrgSwitcher },
  // { tagName: 'coral-shell-solution', component: ShellSolution, extendsElement: 'a' },
  // { tagName: 'coral-shell-solutions', component: ShellSolutions },
  // { tagName: 'coral-shell-solutionswitcher', component: ShellSolutionSwitcher },
  // { tagName: 'coral-shell-suborganization', component: ShellSuborganization },
  // { tagName: 'coral-shell-user', component: ShellUser },
  // { tagName: 'coral-shell-workspace', component: ShellWorkspace, extendsElement: 'a' },
  // { tagName: 'coral-shell-workspaces', component: ShellWorkspaces },
  { tagName: 'coral-sidenav', component: SideNav, extendsElement: 'nav' },
  // { tagName: 'coral-sidenav-item', component: SideNavItem, extendsElement: 'a' },
  // { tagName: 'coral-sidenav-level', component: SideNavLevel },
  { tagName: 'coral-slider', component: Slider },
  // { tagName: 'coral-slider-item', component: SliderItem },
  { tagName: 'coral-splitbutton', component: SplitButton },
  { tagName: 'coral-status', component: Status },
  { tagName: 'coral-step', component: Step },
  { tagName: 'coral-steplist', component: StepList },
  { tagName: 'coral-switch', component: Switch },
  { tagName: 'coral-tab', component: Tab },
  { tagName: 'coral-table', component: Table, extendsElement: 'table' },
  // { tagName: 'coral-table-body', component: TableBody, extendsElement: 'tbody' },
  // { tagName: 'coral-table-cell', component: TableCell, extendsElement: 'td' },
  // { tagName: 'coral-table-column', component: TableColumn, extendsElement: 'col' },
  // { tagName: 'coral-table-foot', component: TableFoot, extendsElement: 'tfoot' },
  // { tagName: 'coral-table-head', component: TableHead, extendsElement: 'thead' },
  // { tagName: 'coral-table-headercell', component: TableHeaderCell, extendsElement: 'th' },
  // { tagName: 'coral-table-row', component: TableRow, extendsElement: 'tr' },
  { tagName: 'coral-tablist', component: TabList },
  { tagName: 'coral-tabview', component: TabView },
  { tagName: 'coral-tag', component: Tag },
  { tagName: 'coral-taglist', component: TagList },
  { tagName: 'coral-textarea', component: Textarea, extendsElement: 'textarea' },
  { tagName: 'coral-textfield', component: Textfield, extendsElement: 'input' },
  { tagName: 'coral-toast', component: Toast },
  { tagName: 'coral-tooltip', component: Tooltip },
  { tagName: 'coral-tree', component: Tree },
  { tagName: 'coral-tree-item', component: TreeItem },
  { tagName: 'coral-wait', component: Wait },
  { tagName: 'coral-wizardview', component: WizardView },
];

export default coralComponents;
