module.exports = {
  CONTAINER_POLICY: {
    tabs: [
      'tab',
    ],
    tabcontent: [
      'helloworld',
      'trophyfield',
      'multifield',
      'fieldset',
      'datepicker',
      'hidden',
      'numberfield',
      'richtext',
      'textarea',
      'textfield',
      'buttongroup',
      'checkbox',
      'radio',
      'select',
      'switchfield',
      'fileupload',
      'pathfield',
      'alerthint',
      'anchorbutton',
      'heading',
    ],
    mf: [
      'textfield',
      'hidden',
      'datepicker',
      'checkbox',
      'radio',
      'select',
      'pathfield',
    ],
    fs: [
      'helloworld',
      'trophyfield',
      'multifield',
      'fieldset',
      'datepicker',
      'hidden',
      'numberfield',
      'richtext',
      'textarea',
      'textfield',
      'buttongroup',
      'checkbox',
      'radio',
      'select',
      'switchfield',
      'fileupload',
      'pathfield',
      'alerthint',
      'anchorbutton',
      'heading',
    ],
  },
};
